#! /bin/sh

# Define startup applications
pgrep -x sxhkd > /dev/null || sxhkd -m 1 &
setxkbmap -layout fr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
xset s off -dpms
picom -b --experimental-backends &
nm-applet &
unclutter --ignore-scrolling --jitter 1 &
dbus-launch dunst --config ~/.config/dunst/dunstrc &
redshift &
~/.config/polybar/launch-bspwm.sh &
wal -R &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         +23
bspc config right_padding       -5
bspc config left_padding        -5
bspc config bottom_padding      -5
bspc config top_monocle_padding 5
bspc config left_monocle_padding 5
bspc config right_monocle_padding 5
bspc config bottom_monocle_padding 5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config single_monocle       true
bspc config focus_follows_pointer   true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a streamlink-twitch-gui state=floating

# Disable rounded corners for fullscreen apps
bspc subscribe desktop_layout | while read -r Event
do
  Desktop=$(echo "$Event" | awk '{print $3}')
  State=$(echo "$Event" | awk '{print $4}')
  if [ "$State" = "monocle" ]; then 
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -f _PICOM_ROUNDED 32c -set _PICOM_ROUNDED 1
    done
  elif [ $(bspc config window_gap) -gt 0 ]; then
    bspc query -N -d $Desktop | while read -r Node
    do
      xprop -id $Node -remove _PICOM_ROUNDED
    done
  fi
done &
